.TH Speed 1 "January 23, 2025"
.SH NAME
Speed
.SH SYNOPSIS
.B speed [options] origin destination
.SH DESCRIPTION
.B Speed
is a simple, tasked file-copying machine.
.SH OPTIONS
.TP
.BI --bytes " bytes"
Specify the number of bytes to read().
.TP
.BI --make-destination
Create the destination as a directory.
.TP
.BI --overwrite
Write existing destination(s).
.TP
.BI --recursive
Copy directories. The destination directories will be created even
if --make-destination is not specified.
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
