.TH Speed 1 "May 8, 2024"
.SH NAME
Speed
.SH SYNOPSIS
.B speed [options] origin destination
.SH DESCRIPTION
.B Speed
is a simple, tasked file-copying machine.
.SH OPTIONS
.TP
.BI --bytes " bytes"
Specify the number of bytes to read().
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
